services:
  postgres:
    image: postgres:16
    container_name: regpay-postgres
    environment:
      POSTGRES_USER: regpay
      POSTGRES_PASSWORD: regpay
      POSTGRES_DB: regpay_db
    ports:
      - "5435:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U regpay"]
      interval: 5s
      timeout: 3s
      retries: 10

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: regpay-kafka
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:29093
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:29093,EXTERNAL://:19093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:19094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
    ports:
      - "19093:19093"
      - "19094:9092"
    healthcheck:
      test: ["CMD", "kafka-broker-api-versions", "--bootstrap-server", "kafka:9092"]
      interval: 10s
      timeout: 5s
      retries: 10

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: regpay-service
    depends_on:
      postgres:
        condition: service_healthy
      kafka:
        condition: service_healthy
    environment:
      APP_PORT: "3003"
      DB_URL: "postgres://regpay:regpay@postgres:5432/regpay_db?sslmode=disable"
      KAFKA_BROKERS: "kafka:9092"
      KAFKA_TOPIC_REG_CREATED: "registration.created"
      KAFKA_TOPIC_PAY_UPLOADED: "payment.uploaded"
      KAFKA_TOPIC_PAY_VERIFIED: "payment.verified"
      KAFKA_TOPIC_REG_CONFIRMED: "registration.confirmed"
      KAFKA_TOPIC_REG_CANCELLED: "registration.cancelled"
      KAFKA_TOPIC_EVENT_STATUS: "event.status.changed"
    ports:
      - "3003:3003"

volumes:
  pgdata:


